- hosts: all
  vars: 
    package: 
      - httpd
      - wget
      - tree
      - git
  tasks: 
  - name: Install packeges
    yum:
      name: "{{ package }}"
      state: latest

  - name: Start apache
    service:
      name: httpd
      state: started
   