- hosts: all
  tasks: 
  - name: Install packeges
    yum:
      name: httpd
      state: latest
    register: hello 
    ignore_errors: yes

  - name: Start apache
    service:
      name: httpd
      state: started
    register: kaizen

  - debug: msg={{ hello }}
  - debug: msg={{ kaizen }}